-- Your SQL goes here
CREATE TABLE IF NOT EXISTS game_bundles (
    member_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    bundle_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL
);

-- Your SQL goes here
CREATE TABLE IF NOT EXISTS game_dlcs (
    main_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    dlc_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL
);


ALTER TABLE products ADD COLUMN total_rating DOUBLE PRECISION NULL DEFAULT NULL;
ALTER TABLE products ADD COLUMN game_type INTEGER NULL DEFAULT NULL;
ALTER TABLE products ADD COLUMN parent_game INTEGER REFERENCES products(id) ON DELETE CASCADE NULL DEFAULT NULL;