CREATE TABLE IF NOT EXISTS game_bundles (
    id SERIAL PRIMARY KEY,
    member_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    bundle_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    UNIQUE (member_id, bundle_id)
);

CREATE TABLE IF NOT EXISTS game_dlcs (
    id SERIAL PRIMARY KEY,
    main_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    dlc_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    UNIQUE (main_id, dlc_id)
);


ALTER TABLE products ADD COLUMN total_rating DOUBLE PRECISION NULL DEFAULT NULL;
ALTER TABLE products ADD COLUMN game_type INTEGER NULL DEFAULT NULL;
ALTER TABLE products ADD COLUMN parent_game INTEGER REFERENCES products(id) ON DELETE CASCADE NULL DEFAULT NULL;