-- This file should undo anything in `up.sql`
DROP TABLE IF EXISTS covers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS releases CASCADE;
DROP TABLE IF EXISTS platform CASCADE;