CREATE TABLE IF NOT EXISTS covers (
    id          INTEGER PRIMARY KEY        NOT NULL,
    image_url   TEXT                    NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id          INTEGER PRIMARY KEY        NOT NULL,
    name        TEXT                    NOT NULL,
    summary     TEXT                    NOT NULL,
    first_release_date INTEGER,
    cover_id    INTEGER 
);

CREATE TABLE IF NOT EXISTS sales (
    id          INTEGER PRIMARY KEY        NOT NULL,
    created_at  TIMESTAMP DEFAULT now() NOT NULL,
    product_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    total_price INTEGER                 NOT NULL
);

CREATE TABLE IF NOT EXISTS releases (
    id          INTEGER PRIMARY KEY      NOT NULL,
    release_date INTEGER,
    product_id  INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    platform INTEGER NOT NULL,
    release_status INTEGER,
    release_region INTEGER
);

CREATE TABLE IF NOT EXISTS platforms (
    id INTEGER PRIMARY KEY NOT NULL,
    abbreviation TEXT,
    name TEXT NOT NULL,
    generation INTEGER
);

CREATE TABLE IF NOT EXISTS regions (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY generated by default as identity(increment by 1 start 1 
    minvalue 1 maxvalue 2147483647 cache 1),
    user_login TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users_have_releases (
    release_id  INTEGER REFERENCES releases(id) ON DELETE CASCADE NOT NULL,
    user_login  TEXT REFERENCES users(user_login) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (release_id, user_login)
);

CREATE TABLE IF NOT EXISTS screenshots (
    id          INTEGER PRIMARY KEY        NOT NULL,
    image_url   TEXT                    NOT NULL,
    game INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL
);